version: '3.8'

services:
    app:
        build:
            context: .
            args:
                UID: ${UID}
                GID: ${GID}
        container_name: message-request_php
        user: "${UID}:${GID}"
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ${PWD}:/var/www
        networks:
            - laravel

    web:
        image: nginx:latest
        container_name: message-request_nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: message-request_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:

volumes:
    db_data:
